import type { UserScriptMeta } from './parser';
import { GM_XMLHTTPREQUEST_BACKGROUND_HANDLER } from './shims/gm-xmlhttprequest';
import { GM_NOTIFICATION_BACKGROUND_HANDLER, GM_OPEN_IN_TAB_BACKGROUND_HANDLER } from './shims/gm-misc';

export function buildBackgroundScript(meta: UserScriptMeta): string | null {
  const handlers: string[] = [];

  const grants = new Set(meta.grants);

  if (grants.has('GM_xmlhttpRequest') || grants.has('GM.xmlHttpRequest')) {
    handlers.push(GM_XMLHTTPREQUEST_BACKGROUND_HANDLER.trim());
  }

  if (grants.has('GM_notification') || grants.has('GM.notification')) {
    handlers.push(GM_NOTIFICATION_BACKGROUND_HANDLER.trim());
  }

  if (grants.has('GM_openInTab') || grants.has('GM.openInTab')) {
    handlers.push(GM_OPEN_IN_TAB_BACKGROUND_HANDLER.trim());
  }

  if (handlers.length === 0) return null;

  return (
    `// Generated by script2extension — background service worker\n` +
    `// Script: ${meta.name} v${meta.version}\n\n` +
    handlers.join('\n\n') +
    '\n'
  );
}
