import type { UserScriptMeta } from './parser';
import { GM_XMLHTTPREQUEST_CONTENT_SHIM } from './shims/gm-xmlhttprequest';
import { GM_STORAGE_SHIM } from './shims/gm-storage';
import { GM_STYLE_SHIM } from './shims/gm-style';
import {
  GM_NOTIFICATION_SHIM,
  GM_SET_CLIPBOARD_SHIM,
  GM_OPEN_IN_TAB_SHIM,
  GM_INFO_SHIM,
  GM_LOG_SHIM,
} from './shims/gm-misc';

export interface ShimLogEntry {
  original: string;
  replacement: string;
}

export interface TransformResult {
  contentJs: string;
  needsBackground: boolean;
  shimLog: ShimLogEntry[];
}

/** Map each @grant value to its content-script shim code */
const CONTENT_SHIM_MAP: Record<string, { shim: string; replacement: string }> = {
  GM_xmlhttpRequest: {
    shim: GM_XMLHTTPREQUEST_CONTENT_SHIM,
    replacement: 'chrome.runtime.sendMessage (via background fetch)',
  },
  'GM.xmlHttpRequest': {
    shim: GM_XMLHTTPREQUEST_CONTENT_SHIM,
    replacement: 'chrome.runtime.sendMessage (via background fetch)',
  },
  GM_setValue: {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  GM_getValue: {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  'GM.setValue': {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  'GM.getValue': {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  GM_deleteValue: {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  GM_listValues: {
    shim: GM_STORAGE_SHIM,
    replacement: 'chrome.storage.local',
  },
  GM_addStyle: {
    shim: GM_STYLE_SHIM,
    replacement: 'DOM <style> injection',
  },
  'GM.addStyle': {
    shim: GM_STYLE_SHIM,
    replacement: 'DOM <style> injection',
  },
  GM_notification: {
    shim: GM_NOTIFICATION_SHIM,
    replacement: 'chrome.notifications (via background)',
  },
  'GM.notification': {
    shim: GM_NOTIFICATION_SHIM,
    replacement: 'chrome.notifications (via background)',
  },
  GM_setClipboard: {
    shim: GM_SET_CLIPBOARD_SHIM,
    replacement: 'navigator.clipboard.writeText',
  },
  'GM.setClipboard': {
    shim: GM_SET_CLIPBOARD_SHIM,
    replacement: 'navigator.clipboard.writeText',
  },
  GM_openInTab: {
    shim: GM_OPEN_IN_TAB_SHIM,
    replacement: 'chrome.tabs.create (via background)',
  },
  'GM.openInTab': {
    shim: GM_OPEN_IN_TAB_SHIM,
    replacement: 'chrome.tabs.create (via background)',
  },
  GM_info: {
    shim: GM_INFO_SHIM,
    replacement: 'static GM_info object',
  },
  'GM.info': {
    shim: GM_INFO_SHIM,
    replacement: 'static GM_info object',
  },
  GM_log: {
    shim: GM_LOG_SHIM,
    replacement: 'console.log',
  },
};

function stripUserScriptBlock(text: string): string {
  return text.replace(/\/\/\s*==UserScript==[\s\S]*?\/\/\s*==\/UserScript==\n?/, '');
}

export function transformScript(text: string, meta: UserScriptMeta): TransformResult {
  const shimLog: ShimLogEntry[] = [];
  const injectedShimSources = new Set<string>();
  const shimSnippets: string[] = [];

  // Deduplicate: storage shim covers multiple grant values
  for (const grant of meta.grants) {
    const entry = CONTENT_SHIM_MAP[grant];
    if (!entry) continue;

    if (!injectedShimSources.has(entry.shim)) {
      injectedShimSources.add(entry.shim);
      shimSnippets.push(entry.shim.trim());
    }

    shimLog.push({ original: grant, replacement: entry.replacement });
  }

  const scriptBody = stripUserScriptBlock(text).trim();

  const shimSection = shimSnippets.length > 0
    ? `// ── GM_* SHIMS ──────────────────────────────────────────\n${shimSnippets.join('\n\n')}\n// ── END SHIMS ───────────────────────────────────────────\n\n`
    : '';

  const contentJs =
    `// Generated by script2extension\n` +
    `// Original script: ${meta.name} v${meta.version}\n\n` +
    `(function() {\n` +
    `  'use strict';\n\n` +
    shimSection +
    `// ── ORIGINAL SCRIPT ─────────────────────────────────────\n` +
    scriptBody + '\n' +
    `\n})();\n`;

  // Background.js is only needed if certain grants are used
  const needsBackground =
    meta.grants.some(g =>
      g === 'GM_xmlhttpRequest' ||
      g === 'GM.xmlHttpRequest' ||
      g === 'GM_notification' ||
      g === 'GM.notification' ||
      g === 'GM_openInTab' ||
      g === 'GM.openInTab'
    );

  return {
    contentJs,
    needsBackground,
    shimLog,
  };
}
